version: "3.9"
services:
  load_balancer:
    image: nginx:alpine
    depends_on:
      - web
      - db
    volumes:
      - ./docker/load_balancer/dhparam.pem:/etc/nginx/dhparam.pem
      - ./docker/load_balancer/lb.conf:/etc/nginx/nginx.conf
      - ./docker/ssl/server.crt:/etc/ssl/certs/lampy.crt
      - ./docker/ssl/server.key:/etc/ssl/private/lampy.key
    ports:
      - "80:80"
      - "443:443"

  web:
    build: docker/php-apache
    volumes:
      - ./presta_app:/var/www/html
      - ./docker/php-apache/lampy.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/ssl/server.crt:/etc/apache2/lampy.crt
      - ./docker/ssl/server.key:/etc/apache2/lampy.key
    links:
      - "db:database"
    scale: 3
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_USER=prestashopuser
      - MYSQL_PASSWORD=biznesbaza
      - MYSQL_DATABASE=prestashop
      - PS_SHOP_DOMAIN=${PS_SHOP_DOMAIN}
    volumes:
      - ./docker/db/.db_data:/var/lib/mysql
      - ./backups/prestashop.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./docker/db/update_domain.sh:/docker-entrypoint-initdb.d/update_domain.sh
    ports:
      - "3307:3306"
