version: "3.9"
services:
    web:
        build: php-apache
        ports: 
            - "80:80"
            - "443:443"
        depends_on:
            - db
        volumes:
            - ../presta_app:/var/www/html
            - ./httpd.conf:/etc/httpd/conf/httpd.conf
    db:
        image: mariadb:latest
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=True
            - MYSQL_USER=prestashopuser
            - MYSQL_PASSWORD=biznesbaza
            - MYSQL_DATABASE=prestashop
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3307:3306"
