version: "3.9"
services:
    web:
        image: nginx:latest
        ports: 
            - "80:80"
            - "443:443"
        depends_on:
            - db
        volumes:
            - ../presta_app:/prestashop
            - ./site.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mariadb:latest
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=True
            - MYSQL_USER=prestashopuser
            - MYSQL_PASSWORD=biznesbaza
            - MYSQL_DATABASE=prestashop
        volumes:
            - ../backups/prestashop.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
    php:
        build: php
        volumes:
            - ../presta_app:/prestashop
        
